# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pNxDAsgfebr1OjWlY-iRt1ur3hjO3wvT

Tahun kabisat terjadi 4 tahun sekali. Sehingga, yang tergolong tahun kabisat adalah tahun yang dapat dibagi 4 dan dibagi 400. Meskipun 4 dan 100 merupakan faktor dari 400, tahun yang dapat habis dibagi 100 bukan merupakan tahun kabisat. Seperti tahun 1900. 
Berikut ini program untuk menentukan tahun kabisat. Dengan inputan user.
"""

def thn_kab(tahun):
  if tahun%400==0:
    print ("Tahun", tahun, "merupakan Tahun Kabisat")
    return True
  elif tahun%4==0:
    if tahun%100==0:
      print("Tahun", tahun, "bukan merupakan Tahun Kabisat")
      return False
    else:
      print("Tahun", tahun,"merupakan Tahun Kabisat")
      return True
  else :
    print("Tahun",tahun, "bukan merupakan Tahun Kabisat")
    return False

try:
  th=int(input("Masukkan Tahun : "))
except:
  print("Masukkan harus berupa angka !!")
hasil = thn_kab(th)

"""Test data untuk tahun-tahun tertentu :"""

tesData = [1900, 2000, 2016, 1987]
tesHasil = [False, True, True, False]
for i in range(len(tesData)):
	thn = tesData[i]
	print(thn,"->",end="")
	hsl = thn_kab(thn)
	if hsl == tesHasil[i]:
		print("TRUE")
	else:
		print("FALSE")
